import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { readdir, readFile } from "node:fs/promises";
import test from "node:test";

const canonical = JSON.parse(
  await readFile(new URL("../dist/canonical.json", import.meta.url), "utf8")
);
const tokensCss = await readFile(new URL("../dist/tokens.css", import.meta.url), "utf8");
const tokenNamesDts = await readFile(new URL("../dist/token-names.d.ts", import.meta.url), "utf8");
const metadata = JSON.parse(
  await readFile(new URL("../dist/metadata.json", import.meta.url), "utf8")
);
const tokenDocs = JSON.parse(
  await readFile(new URL("../dist/token-docs.json", import.meta.url), "utf8")
);
const buildReport = JSON.parse(
  await readFile(new URL("../dist/build-report.json", import.meta.url), "utf8")
);
const tokenQuality = JSON.parse(
  await readFile(new URL("../dist/token-quality.json", import.meta.url), "utf8")
);
const tokenQualityMarkdown = await readFile(
  new URL("../dist/token-quality.md", import.meta.url),
  "utf8"
);

test("generated canonical JSON contains core token groups", () => {
  assert.ok(canonical.tokens.color.primitive);
  assert.ok(canonical.tokens.color.semantic);
  assert.ok(canonical.tokens.space);
  assert.ok(canonical.tokens.radius);
  assert.ok(canonical.tokens.shadow);
  assert.ok(canonical.tokens.typography);
});

test("semantic colour tokens contain light and dark mode values", () => {
  assert.deepEqual(Object.keys(canonical.tokens.color.semantic.text.default.value).sort(), [
    "dark",
    "light"
  ]);
});

test("canonical JSON does not contain source-only forbidden markers", () => {
  const serialized = JSON.stringify(canonical);
  for (const marker of [
    "$extensions",
    "com.figma",
    "VariableID",
    "VariableCollectionId",
    "targetVariable",
    "PRIVATE_COMPANY_NAME_PLACEHOLDER"
  ]) {
    assert.equal(serialized.includes(marker), false, `${marker} should not be present`);
  }
});

test("generated CSS contains expected custom properties", () => {
  assert.match(tokensCss, /Generated by @demo-ds\/token-pipeline/u);
  assert.match(tokensCss, /--ds-color-text-default: #083344;/u);
  assert.match(tokensCss, /--ds-space-md: 8px;/u);
  assert.match(tokensCss, /--ds-radius-md: 8px;/u);
  assert.match(tokensCss, /--ds-shadow-card: 0px 2px 8px 0px rgb\(15 23 42 \/ 0\.12\);/u);
  assert.match(tokensCss, /--ds-font-size-heading-h1: 32px;/u);
});

test("generated CSS contains light and dark Mantine colour-scheme selectors", () => {
  assert.match(tokensCss, /\[data-mantine-color-scheme='light'\]/u);
  assert.match(tokensCss, /\[data-mantine-color-scheme='dark'\]/u);
  assert.match(
    tokensCss,
    /\[data-mantine-color-scheme='dark'\] \{\n(?:.*\n)*? {2}--ds-color-text-default: #FDFDFD;/u
  );
});

test("generated TypeScript declarations include token-name union members", () => {
  assert.match(tokenNamesDts, /export type TokenName =/u);
  assert.match(tokenNamesDts, /"color\.semantic\.text\.default"/u);
  assert.match(tokenNamesDts, /"space\.md"/u);
  assert.match(tokenNamesDts, /"radius\.md"/u);
  assert.match(tokenNamesDts, /"shadow\.card"/u);
  assert.match(tokenNamesDts, /"typography\.heading\.h1"/u);
});

test("generated metadata contains deterministic package summary", () => {
  assert.equal(metadata.name, "demo-design-system-tokens");
  assert.equal(metadata.source, "demo-design-token-fixtures");
  assert.equal(metadata.meta.generatedBy, "@demo-ds/token-pipeline");
  assert.deepEqual(metadata.modes, ["light", "dark"]);
  assert.deepEqual(metadata.categories, ["color", "radius", "shadow", "space", "typography"]);
  assert.equal(metadata.tokenCount, 223);
});

test("generated build report explains pipeline output", () => {
  assert.equal(buildReport.sourceRecordsRead, 479);
  assert.equal(buildReport.tokensGenerated, metadata.tokenCount);
  assert.deepEqual(buildReport.semanticTokensMissingModes, []);
  assert.ok(buildReport.recordsMapped > 0);
  assert.equal(buildReport.recordsSkipped, 0);
  assert.ok(buildReport.generatedFiles.includes("canonical.json"));
  assert.ok(buildReport.generatedFiles.includes("build-report.json"));
  assert.ok(buildReport.generatedFiles.includes("token-quality.json"));
  assert.ok(buildReport.generatedFiles.includes("token-quality.md"));
  assert.ok(buildReport.generatedFiles.includes("tokens.css"));
  assert.ok(
    buildReport.renamedPaths.some(
      (entry) =>
        entry.sourcePath === "Font colours.Default text" &&
        entry.canonicalPath === "color.semantic.text.default"
    )
  );
});

test("generated token quality report explains contract health", () => {
  assert.equal(tokenQuality.meta.generatedBy, "@demo-ds/token-pipeline");
  assert.equal(tokenQuality.status, "pass");
  assert.equal(tokenQuality.summary.tokenCount, metadata.tokenCount);
  assert.equal(tokenQuality.summary.sourceRecordsRead, buildReport.sourceRecordsRead);
  assert.equal(tokenQuality.summary.recordsSkipped, 0);
  assert.equal(tokenQuality.summary.errorCount, 0);
  assert.equal(tokenQuality.css.coveragePercent, 100);
  assert.equal(tokenQuality.css.tokensWithoutCssOutput.length, 0);
  assert.equal(tokenQuality.modes.semanticColors.missing.length, 0);
  assert.equal(tokenQuality.modes.shadows.missing.length, 0);
  assert.ok(tokenQuality.source.generatedFiles.includes("token-quality.json"));
  assert.ok(
    tokenQuality.source.files.some(
      (file) => file.file === "tokens/Light.tokens.json" && file.mappedRecords > 0
    )
  );
});

test("generated token quality markdown is review-friendly", () => {
  assert.match(tokenQualityMarkdown, /Generated by @demo-ds\/token-pipeline/u);
  assert.match(tokenQualityMarkdown, /# Token Quality Report/u);
  assert.match(tokenQualityMarkdown, /Status: \*\*pass\*\*/u);
  assert.match(tokenQualityMarkdown, /## Mode Coverage/u);
  assert.match(tokenQualityMarkdown, /No findings\./u);
});

test("generated token docs are consumable without scraping CSS", () => {
  const semanticTextGroup = tokenDocs.groups.find((group) => group.name === "color.semantic.text");
  assert.ok(semanticTextGroup);
  assert.ok(
    semanticTextGroup.tokens.some(
      (token) =>
        token.name === "color.semantic.text.default" &&
        token.cssVariable === "--ds-color-text-default" &&
        token.value.light === "#083344" &&
        token.value.dark === "#FDFDFD"
    )
  );
  const shadowGroup = tokenDocs.groups.find((group) => group.name === "shadow.card");
  assert.ok(shadowGroup);
  assert.ok(
    shadowGroup.tokens.some(
      (token) =>
        token.name === "shadow.card" &&
        token.cssVariable === "--ds-shadow-card" &&
        token.value.light.blur === 8 &&
        token.value.dark.blur === 8
    )
  );
});

test("generated token outputs are deterministic", async () => {
  const before = await hashDistFiles();
  execFileSync(
    "node",
    [
      "../token-pipeline/dist/cli/buildCanonical.js",
      "./fixtures/extracted",
      "./dist",
      "../../token-pipeline.config.json"
    ],
    {
      cwd: new URL("..", import.meta.url),
      stdio: "pipe"
    }
  );
  const after = await hashDistFiles();

  assert.deepEqual(after, before);
});

async function hashDistFiles() {
  const distUrl = new URL("../dist/", import.meta.url);
  const files = (await readdir(distUrl)).filter((file) =>
    [
      "build-report.json",
      "canonical.json",
      "index.d.ts",
      "index.js",
      "metadata.json",
      "token-docs.json",
      "token-quality.json",
      "token-quality.md",
      "token-names.d.ts",
      "token-names.js",
      "tokens.css",
      "tokens.dark.css",
      "tokens.light.css"
    ].includes(file)
  );

  const hashes = {};
  for (const file of files.sort()) {
    const contents = await readFile(new URL(file, distUrl));
    hashes[file] = createHash("sha256").update(contents).digest("hex");
  }
  return hashes;
}
