import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

import type { CanonicalColorToken, CanonicalToken, CanonicalTokenDocument } from "./types.js";
import { collectCanonicalTokens } from "./validateCanonicalTokens.js";

const generatedHeader = [
  "Generated by @demo-ds/token-pipeline.",
  "Do not edit directly.",
  "Source: demo-design-token-fixtures."
];

export interface OutputOptions {
  readonly outputDirectory: string;
}

export async function generateTokenOutputs(
  document: CanonicalTokenDocument,
  options: OutputOptions
): Promise<void> {
  await mkdir(options.outputDirectory, { recursive: true });
  const tokens = collectCanonicalTokens(document);

  const outputs: Record<string, string> = {
    "canonical.json": `${JSON.stringify(document, null, 2)}\n`,
    "tokens.css": generateCombinedCss(tokens),
    "tokens.light.css": generateModeCss(tokens, "light"),
    "tokens.dark.css": generateModeCss(tokens, "dark"),
    "index.js": generateIndexJs(document, tokens),
    "index.d.ts": generateIndexDts(tokens),
    "token-names.js": generateTokenNamesJs(tokens),
    "token-names.d.ts": generateTokenNamesDts(tokens),
    "metadata.json": `${JSON.stringify(generateMetadata(document, tokens), null, 2)}\n`,
    "token-docs.json": `${JSON.stringify(generateTokenDocs(document, tokens), null, 2)}\n`
  };

  for (const [fileName, contents] of Object.entries(outputs).sort(([left], [right]) =>
    left.localeCompare(right)
  )) {
    await writeFile(join(options.outputDirectory, fileName), contents, "utf8");
  }
}

function generateCombinedCss(tokens: readonly CanonicalToken[]): string {
  return [
    cssHeader(),
    ":root {",
    ...indent(rootDeclarations(tokens)),
    "}",
    "",
    "[data-mantine-color-scheme='light'] {",
    ...indent(semanticColorDeclarations(tokens, "light")),
    "}",
    "",
    "[data-mantine-color-scheme='dark'] {",
    ...indent(semanticColorDeclarations(tokens, "dark")),
    "}",
    ""
  ].join("\n");
}

function generateModeCss(tokens: readonly CanonicalToken[], mode: "light" | "dark"): string {
  return [
    cssHeader(),
    ":root {",
    ...indent([...rootDeclarations(tokens), ...semanticColorDeclarations(tokens, mode)].sort()),
    "}",
    ""
  ].join("\n");
}

function rootDeclarations(tokens: readonly CanonicalToken[]): string[] {
  return [
    ...tokens.filter(isPrimitiveColorToken).map((token) => cssDeclaration(token, token.value)),
    ...tokens.filter(isDimensionToken).map((token) => cssDeclaration(token, formatDimensionValue(token))),
    ...tokens.flatMap((token) => typographyDeclarations(token))
  ].sort();
}

function semanticColorDeclarations(
  tokens: readonly CanonicalToken[],
  mode: "light" | "dark"
): string[] {
  return tokens
    .filter(isSemanticColorToken)
    .map((token) => {
      const value = token.value;
      return cssDeclaration(token, typeof value === "string" ? value : value[mode]);
    })
    .sort();
}

function generateIndexJs(document: CanonicalTokenDocument, tokens: readonly CanonicalToken[]): string {
  return [
    jsHeader(),
    `export const tokens = ${json(tokensToPublicMap(tokens))};`,
    `export const tokenNames = ${json(tokenNames(tokens))};`,
    `export const tokenNameToCssVariable = ${json(tokenNameToCssVariable(tokens))};`,
    `export const metadata = ${json(generateMetadata(document, tokens))};`,
    "",
    "export function cssVar(name) {",
    "  const cssVariable = tokenNameToCssVariable[name];",
    "  if (cssVariable === undefined) {",
    "    throw new Error(`Unknown token name: ${name}`);",
    "  }",
    "  return `var(${cssVariable})`;",
    "}",
    ""
  ].join("\n");
}

function generateIndexDts(tokens: readonly CanonicalToken[]): string {
  return [
    tsHeader(),
    "import type { TokenName } from './token-names.js';",
    "",
    "export { tokenNames, tokenNameToCssVariable } from './token-names.js';",
    "export type { TokenName } from './token-names.js';",
    "export declare const tokens: Record<string, unknown>;",
    "export declare const metadata: {",
    "  readonly meta: {",
    "    readonly generatedBy: string;",
    "    readonly doNotEdit: boolean;",
    "    readonly source: string;",
    "  };",
    "  readonly name: string;",
    "  readonly source: string;",
    "  readonly tokenCount: number;",
    "  readonly modes: readonly string[];",
    "  readonly categories: readonly string[];",
    "};",
    "export declare function cssVar(name: TokenName): string;",
    ""
  ].join("\n");
}

function generateTokenNamesJs(tokens: readonly CanonicalToken[]): string {
  return [
    jsHeader(),
    `export const tokenNames = ${json(tokenNames(tokens))};`,
    `export const tokenNameToCssVariable = ${json(tokenNameToCssVariable(tokens))};`,
    ""
  ].join("\n");
}

function generateTokenNamesDts(tokens: readonly CanonicalToken[]): string {
  const names = tokenNames(tokens);
  return [
    tsHeader(),
    "export type TokenName =",
    ...names.map((name, index) => `  ${index === 0 ? "" : "| "}${JSON.stringify(name)}`),
    ";",
    "",
    "export declare const tokenNames: readonly TokenName[];",
    "export declare const tokenNameToCssVariable: Readonly<Partial<Record<TokenName, string>>>;",
    ""
  ].join("\n");
}

function generateMetadata(document: CanonicalTokenDocument, tokens: readonly CanonicalToken[]) {
  return {
    meta: {
      generatedBy: "@demo-ds/token-pipeline",
      doNotEdit: true,
      source: document.meta.source
    },
    name: document.meta.name,
    source: document.meta.source,
    tokenCount: tokens.length,
    modes: document.modes,
    categories: Object.keys(document.tokens).sort()
  };
}

function generateTokenDocs(document: CanonicalTokenDocument, tokens: readonly CanonicalToken[]) {
  const groups = new Map<string, CanonicalToken[]>();

  for (const token of tokens) {
    const groupName = token.path.slice(0, token.type === "color" ? 3 : 2).join(".");
    groups.set(groupName, [...(groups.get(groupName) ?? []), token]);
  }

  return {
    meta: {
      generatedBy: "@demo-ds/token-pipeline",
      doNotEdit: true,
      source: document.meta.source
    },
    groups: [...groups.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([name, groupTokens]) => ({
        name,
        tokens: groupTokens
          .sort((left, right) => left.name.localeCompare(right.name))
          .map((token) => ({
            name: token.name,
            type: token.type,
            cssVariable: token.cssVariable,
            value: token.value,
            unit: "unit" in token ? token.unit : undefined
          }))
      }))
  };
}

function tokensToPublicMap(tokens: readonly CanonicalToken[]): Record<string, unknown> {
  const root: Record<string, unknown> = {};

  for (const token of [...tokens].sort((left, right) => left.name.localeCompare(right.name))) {
    let cursor = root;
    for (const segment of token.path.slice(0, -1)) {
      cursor[segment] ??= {};
      cursor = cursor[segment] as Record<string, unknown>;
    }

    cursor[token.path[token.path.length - 1]] = {
      name: token.name,
      path: token.path,
      type: token.type,
      value: token.value,
      cssVariable: token.cssVariable,
      unit: "unit" in token ? token.unit : undefined
    };
  }

  return root;
}

function tokenNames(tokens: readonly CanonicalToken[]): string[] {
  return tokens.map((token) => token.name).sort();
}

function tokenNameToCssVariable(tokens: readonly CanonicalToken[]): Record<string, string> {
  const entries: Array<[string, string]> = [];
  for (const token of tokens) {
    if (token.cssVariable !== undefined) {
      entries.push([token.name, token.cssVariable]);
    }
  }
  return Object.fromEntries(entries.sort(([left], [right]) => left.localeCompare(right)));
}

function typographyDeclarations(token: CanonicalToken): string[] {
  if (token.type !== "typography") {
    return [];
  }

  const suffix = token.path.slice(1).join("-");
  return [
    `--ds-font-size-${suffix}: ${token.value.fontSize}px;`,
    `--ds-line-height-${suffix}: ${token.value.lineHeight}px;`,
    `--ds-font-weight-${suffix}: ${token.value.fontWeight};`
  ];
}

function cssDeclaration(token: CanonicalToken, value: unknown): string {
  return `${token.cssVariable}: ${value};`;
}

function formatDimensionValue(token: CanonicalToken): string {
  if (token.type !== "dimension" && token.type !== "radius") {
    throw new Error(`Expected dimension token: ${token.name}`);
  }
  return `${token.value}${token.unit}`;
}

function isPrimitiveColorToken(token: CanonicalToken): token is CanonicalColorToken {
  return token.type === "color" && token.path[0] === "color" && token.path[1] === "primitive";
}

function isSemanticColorToken(token: CanonicalToken): token is CanonicalColorToken {
  return token.type === "color" && token.path[0] === "color" && token.path[1] === "semantic";
}

function isDimensionToken(token: CanonicalToken): boolean {
  return token.type === "dimension" || token.type === "radius";
}

function cssHeader(): string {
  return generatedHeader.map((line) => `/* ${line} */`).join("\n");
}

function jsHeader(): string {
  return generatedHeader.map((line) => `// ${line}`).join("\n");
}

function tsHeader(): string {
  return jsHeader();
}

function indent(lines: readonly string[]): string[] {
  return lines.map((line) => `  ${line}`);
}

function json(value: unknown): string {
  return JSON.stringify(value, null, 2);
}
